### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sirkadirov** [SirkadirovTeam/SimplePM_WebApp#14]
- [x]  Редактирование прав пользователей
- [x]  Возможность импорта JSON файла с тестами к задаче
- [x]  Сконфигурировать отображение пользователей сайта в блоке "Кто онлайн?" и "Дни рождения"
- [ ]  Реализовать возможность измерения плагиата у пользователей системы
- [x]  Добавить сервис домашних заданий, реализовать соответствующий функционал
- [x]  Реализовать поддержку проведения турниров по правилам ACM и ACM Plus
- [x]  Реализовать различные плюшки
- [x]  Доделать всё не доделанное и всё в этом духе
